# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcf838c871475a980381b3f6c9aa460afa21b62e3bcd4d81b76766184cfd24d64257c3b888acc466d5eafd6d55b6b72cd1bba815602e63cffce29d1091be9ee8

test:
  secret_key_base: 1ee4f6ef069d514120f2d5c2c0cf97ae3fe1d3c7e08fec1ce038eaa3a89bb0624b6cc0809c130a74a499d8b98027c4e523359935348403554df0148f703f58ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
